version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "15432:5432"
    volumes:
      - pg-data:/var/lib/postgresql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "13306:3306"
    volumes:
      - my-data:/var/lib/mysql

volumes:
  my-data:
  pg-data:
